const BASE_URL = "https://api-dev-loptelink.aigoox.com/"
const BASE_URL_DEV = "http://127.0.0.1:8000/"
const API = BASE_URL_DEV + "api/"

export const URL_ADS = API + "ads"
export const URL_AD = API + "ad"
export const URL_LINK = API + "link"
export const URL_SEARCH_LINK = API + "search_links"
export const URL_LINKS = API + "links"
export const URL_CONFIG = API + "config"
export const URL_CONFIG_BY_USER = API + "config_by_user"
export const DOMAIN_LINK = "https://link.aigoox.com/"
export const DOMAIN_LINK_DEV = "https://dev-link.aigoox.com/"