export const VALIDATE_DELETE_SUCCESS = "Xóa dữ liệu thành công"
export const VALIDATE_ADD_SUCCESS = "Thêm dữ liệu thành công"
export const VALIDATE_EXIST_DATA = "Dữ liệu đã tồn tại"
export const VALIDATE_UPDATE_SUCCESS = "Cập nhật dữ liệu thành công"
export const VALIDATE_UPDATE_FAILED = "Cập nhật dữ liệu thất bại"