import Head from "next/head";
import React from "react";
import {TypePropsHeader} from "~/@type/header";

export default function Header({ title }: TypePropsHeader) {
    return <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
    </Head>
}